name: Run Spider

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '25 20 * * *'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'development'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python script
      run: |
        scrapy crawl -s MONGODB_URI="mongodb+srv://m87:Qgl7ypqYRDfthuM7@cluster0.ztxjdbr.mongodb.net/" -s MONGODB_DATABASE="los-tiempos" clasificados_spider
